baseURL = 'https://gannonlawlor.github.io'
languageCode = 'en-us'
title = 'Gannon Lawlor'
theme = "papermod"

[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'

[params.homeInfoParams]
	Title = "Hi there 👋"
	Content = ""